### PR TITLE
Support for AudioReverbFilter

### PR DESCRIPTION
**Pull request by vale7z4387ruwrejmhsr**
as the titel says

### CODE REVIEW

**Comment by ds5678** [comment]
I'm not sure how you came up with this structure, but it's not correct.

Here's a zip file containing type tree comparisons for all assets:

[AllComparisons.zip](https://github.com/AssetRipper/AssetRipper/files/8401349/AllComparisons.zip)

The numbered folders coorespond to ClassIDType numbers. Release is for reading. Editor is for yaml.

**Comment by vale7z4387ruwrejmhsr** [comment]
ok but what number is the AudioReverbFilter than?

**Comment by ds5678** [comment]
> ok but what number is the AudioReverbFilter than?

https://github.com/AssetRipper/AssetRipper/blob/master/AssetRipperCommon/ClassIDType.cs#L155

**Comment by vale7z4387ruwrejmhsr** [comment]
changed it i hope it's correct now

**Comment by ds5678** [comment]
Without even looking at your code, I know it's not because the continuous integration failed.

**Comment by ds5678** [comment]
I notice your version for `m_RoomRolloff` is incorrect. It was first removed in `5.6.0b10`, so all versions less than that have it.

Your `AudioReverbPreset` needs a source url in the comments.

**Comment by ds5678** [comment]
You would probably have a much easier time if you made your commits inside visual studio. You can check compilation and use intellisense. For example, intellisense would make it much easier for you to find:

`version.IsLess(5, 6, 0, UnityVersionType.Beta, 10);`

**Comment by ds5678** [comment]
Also, Unity won't accept your yaml without the `m_` in the name string.

**Comment by vale7z4387ruwrejmhsr** [comment]
ok now i am going to bed see you later

**Comment by ds5678** [comment]
The `m_` is needed in the `"DryLevel"` part. The variable names have no impact on this.

**Comment by vale7z4387ruwrejmhsr** [comment]
ok so in the node

**Comment by vale7z4387ruwrejmhsr** [comment]
so can you merge it now?

**Pull request merged**
