### PR TITLE
[Enhancement] Improve Method Stripping and Script Decompilation to Reduce Compile Errors

### PR DESCRIPTION
**Pull request by Panthr75**
See issue #291

In progress development at fixing method stripping so code generated is usable.
This pull request has been expanded to produce code that has less compiler errors out of the box.

#### All Scripting Levels
- [x] Remove anything with `CompilerGenerated` attribute or `AsyncStateMachine` attribute
- [x] Remove fields/methods with special names (e.g. `<DEBUG_ENABLED>k__backingField`)
- [x] fix casts of generic type to null
- [x] remove `Optional` attributes on parameters and replace them with actual assignments to `default`
- [x] fix `StructLayout(0, ...)` attribute, as it's ambiguous between `StructLayout(short, ...)` and `StructLayout(LayoutKind, ...)`
- [x] **MINOR** - fix generic type constraints if the generic type is used as a pointer (switch from `struct` to `unmanaged`)
- [x] remove some uncaught `IteratorStateMachine` and `AsyncStateMachine` attributes

#### Scripting Level 1
- [x] Ensure interfaces are properly implemented (generate method stubs if needed [e.g, `IDisposable` requires `Dispose` method])
- [x] Ensure abstract members are implemented (generate stubs for implementations)
- [x] Don't strip explicit interface implementations - reduce to stubs
- [x] Strip inner types
- [x] Dont strip enum member definitions from enums
- [x] Implement basic constructors stubs

#### IL2CPP (Scripting Levels 1 & 2)
- [x] Ensure constructor stubs call valid base constructor
- [x] Ensure struct fields are assigned in struct constructor stubs
- [x] Ensure out parameters are set
- [ ] Fix recursive base constructors

#### Overall
- [x] Figure out why some members are skipped for all the processes mentioned here
- [x] Figure out a better way to resolve types, like generic types, for use cases like setting a default parameter.
- [ ] Remove unresolved attributes (like Nullable and NullableContext, as these aren't supported in Unity)

### CODE REVIEW

**Comment by Rikka93** [comment]
Will this be merged soon?

**Comment by cameron-macy** [comment]
Are you going to continue development on this pull even after ds5678 stops working the project?

**Comment by ds5678** [comment]
> Are you going to continue development on this pull even after ds5678 stops working the project?

Unless #376 is a huge failure, I will keep working on the project. There is no immediate danger of the project being abandoned.

**Comment by ds5678** [comment]
@Panthr75 Can you separate your changes for these two files into a new pull request:

* AssetRipper.Fundamentals/Structure/Assembly/Mono/MonoType.cs
* AssetRipper.Fundamentals/Structure/Assembly/Serializable/SerializableType.cs

They don't fit the theme of this pull request, and I've reviewed them. They can be merged now if you make a new pull request.

**Comment by Panthr75** [comment]
@ds5678 Did so at #403. Do you want me to just revert the changes to `AssetRipper.Fundamentals/Structure/Assembly/Mono/MonoType.cs` and `AssetRipper.Fundamentals/Structure/Assembly/Serializable/SerializableType.cs` in this pr?

**Comment by ds5678** [comment]
@Panthr75 You'll have to do a rebase and/or force push in order to resolve the merge conflicts.

**Pull request merged**
