### PR TITLE
Add CLI

### LINKED ISSUE #1343: [Enhancement]: Add Command Line Interface (CLI)
### Describe the new feature or enhancement

Sometimes I want to quickly export all files of a certain type from a game. A cli would be perfect for this. I personally would need it to allow setting all the configuration options using command line parameters as well as having some parameters to select what asset type(s) should be exported.

### PR DESCRIPTION
**Pull request by YoshiRulz**
Change to solution file might be wrong; it was done with `dotnet sln` + hand-fixes.
Also some of the MSBuild props might be specific to ASP.NET and thus useless here.

Resolves #1343.

### CODE REVIEW

**Comment by YoshiRulz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ds5678** [comment]
I don't want the maintenance.

**Comment by YoshiRulz** [comment]
...The maintenance of an 100 LOC shim over existing, core components? That's too much? You're being completely unreasonable.

**Comment by ds5678** [comment]
Specifically, this has multiple recurring maintenance costs:

* An additional 5 / 6 artifacts for every release.
* A premium edition variant, which would need to keep parity.
* Bug reports.
* Barriers to refactoring.

**Comment by YoshiRulz** [comment]
Clearly I'm not going to convince you.

I will keep this branch up for others to use, as well as a Nix expression for it.

**Comment by ds5678** [comment]
> ...The maintenance of an 100 LOC shim over existing, core components? That's too much? You're being completely unreasonable.

This feels like entitlement.

**Pull request closed without merging**
