### PR TITLE
GameBundle: skip failed files

### PR DESCRIPTION
**Pull request by davispuh**
Parsing some files might fail due to various reasons in such case still proceed with remaining files.

### CODE REVIEW

**Comment by ds5678** [comment]
> might fail due to various reasons

I want these listed.

**Comment by davispuh** [comment]
> > might fail due to various reasons
> 
> I want these listed.

One reason can be encrypted `global-metadata.dat`, some games do that.

**Comment by ds5678** [comment]
> > > might fail due to various reasons
> > 
> > I want these listed.
> 
> One reason can be encrypted `global-metadata.dat`, some games do that.

I'd like to see the stack trace for that because I don't think your code would affect an encrypted metadata.

**Comment by ds5678** [comment]
In any case, this is not how I would want this "issue" resolved. I would be more in favor of a `CompressedResourceFile` class that contains the compressed data when decompression fails or some type of "failed file" class. I am not okay with just printing a message into the console.

**Pull request closed without merging**
